---
title: "Hotel Reviews"
author: "Zhichao Hu"
date: "November 8, 2019"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(ggthemes)
```
# load data
```{r}
hotel_reviews <- read_csv("Hotel_Reviews.csv")
```
# date range of all reviews
```{r}
min(mdy(hotel_reviews$Review_Date))
max(mdy(hotel_reviews$Review_Date))
```

# unique hotels in dataset
There are two hotel with the same name but different addresses; address should be used as a unique identifier.
```{r}
hotel_reviews$Hotel_Name %>% unique() %>% length()
hotel_reviews$Hotel_Address %>% unique() %>% length()
```

# hotels with most number of reviews
```{r}
hotel_reviews %>% group_by(Hotel_Address) %>% summarise(name=first(Hotel_Name), count=n()) %>% 
  arrange(desc(count)) %>% select(name, count, Hotel_Address)

```

# summarise related columns to create predictors
```{r}
hotel_agg <- hotel_reviews %>% group_by(Hotel_Address) %>% 
  summarise(name=first(Hotel_Name), 
            review_total=mean(Total_Number_of_Reviews), 
            review_n=mean(Review_Total_Negative_Word_Counts),
            review_p=mean(Review_Total_Positive_Word_Counts), 
            review_m=mean(Additional_Number_of_Scoring),
            reviewer_exp=mean(Total_Number_of_Reviews_Reviewer_Has_Given),
            score=mean(Average_Score))
colnames(hotel_agg)[1] <- "address"
```

# score histgram
```{r}
hotel_agg %>% ggplot(aes(score))+geom_histogram(color="blue", fill="white")+theme_bw()
```

# build linear model
```{r}
lmod <- lm(score~review_total+review_n+review_p+review_m+reviewer_exp, hotel_agg)
```

```{r}
summary(lmod)
```

```{r}

```


